#! /usr/bin/bash

# case study on understanding for condition

# example start and end point

for i in 1 2 3 4 5
do

	echo " The value of 1 is:" $i
done

# example of expressing in series format

echo "---------------Series Output-------------"

for i in {1..20}
do
	echo "The value of i is:" $i
done


